### ISSUE TITLE
Error: "invalid_token" even though I use a fresh token 

### ISSUE THREAD

**Issue by alemens** [transferwise/public-api-postman-collection#13]
# Steps to reproduce 
- Copy API key token on Wise settings account
- Open up a terminal and run following command  
```bash
curl -X GET https://api.sandbox.transferwise.tech/v1/profiles \
     -H "Authorization: Bearer <your api token>"
```
- Be sure in the command above you replaced `<your api token>` with your token API key 

# Expected behaviour 
- Get a response with `profile id`

# Error instead  
```bash
{"error":"invalid_token","error_description":"<your api token>"}
```

**Comment by BrunoBernardino** [comment]
I'm also getting this, have you managed to sort it out @alemens ?

NOTE: It works perfectly when I use it against `https://api.transferwise.com` instead of `https://api.sandbox.transferwise.tech`, so maybe I need to enable the key for the sandbox somewhere?

**Comment by BrunoBernardino** [comment]
For anyone else running into this, you need to create a specific account and key in the sandbox directly, at https://sandbox.transferwise.tech/register (OAuth won't work). I suppose this can be closed.

**Comment by alemens** [comment]
Bruno @BrunoBernardino that works!
